
- name: Install jfrog-ansible-docker-artifactoryartifactory
  hosts: localhost
  roles:
    - ansible-docker-artifactory

- name: Install jfrog-ansible-docker-host
  hosts: localhost
  roles:
    - ansible-docker-host

- name: Install jfrog-ansible-docker-jfrog-xray
  hosts: localhost
  roles:
    - ansible-docker-jfrog-xray



- hosts: artifactory_servers
  collections:
    - jfrog.platform
    - community.general
  roles:
    - artifactory

- hosts: postgres_servers
  collections:
    - community.postgresql
    - community.general
    - jfrog.platform
  roles:
    - postgres

- hosts: artifactory_servers
  collections:
    - community.general
    - jfrog.platform
  serial:
    - 1
    - 100%
  roles:
    - role: artifactory
      when: artifactory_enabled | bool

- hosts: xray_servers
  collections:
    - community.general
    - jfrog.platform
  roles:
    - role: xray
      when: xray_enabled | bool